[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "ffmpeg"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[start]
cmd = "python -m streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
